# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('stack', models.TextField()),
                ('year_of_grad', models.CharField(max_length=4)),
                ('upload', models.FileField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
