# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_grad',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
