# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170522_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='posts',
            new_name='classroom',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumpost', to='forum.Forum'),
        ),
    ]
