# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20170521_1734'),
        ('forum', '0004_auto_20170522_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='classroom.Classroom'),
        ),
    ]
