# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 19:30
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumpost_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='classroom',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classroom.Classroom'),
        ),
    ]
