# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lecture', models.TextField()),
                ('reading', models.TextField(null=True)),
                ('homework_instructions', models.TextField(null=True)),
                ('uploads', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='posted_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classtime',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='session',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='classroom.Classroom'),
        ),
        migrations.AddField(
            model_name='anouncements',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anouncements', to='classroom.Classroom'),
        ),
    ]
