# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_anouncements_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncements',
            name='classrm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anouncements', to='classroom.Classroom'),
        ),
    ]
