# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_anouncements_classrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anouncements',
            old_name='classrm',
            new_name='classroom',
        ),
    ]
