# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20170521_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
