# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20170521_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='homework_instructions',
            new_name='homework',
        ),
    ]
