# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20170521_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'permissions': (('can_enter_classroom', 'Can enter classroom'),)},
        ),
    ]
