# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20170523_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.TextField(blank=True, null=True),
        ),
    ]
