# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20170524_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.TextField(blank=True, null=True),
        ),
    ]
